name: CL-Launcher CI/CD

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]
  workflow_dispatch:

jobs:
  build:
    name: Build & Publish
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup .NET 8.0
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore NuGet packages
      run: >
        dotnet restore "CL(CLegendary Launcher)/CL(CLegendary Launcher).csproj" 
        -r win-x64 
        --force

    - name: Publish Win-x64
      run: >
        dotnet publish "CL(CLegendary Launcher)/CL(CLegendary Launcher).csproj" 
        -c Release 
        -r win-x64 
        --no-restore 
        --self-contained true 
        -o ./publish 
        -p:PublishSingleFile=false 
        -p:PublishReadyToRun=false 
        -p:WarningLevel=0
        -p:DebugType=portable

    # Оскільки нам потрібен ZIP з конкретною структурою
    - name: Create ZIP Archive
      shell: pwsh
      run: |
        Compress-Archive -Path ./publish/* -DestinationPath ./CL-Launcher-Win-x64.zip

    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: CL-Launcher-Build-${{ github.ref_name }}
        path: ./CL-Launcher-Win-x64.zip
